version: "3.9"
name: test_app
services:
  # apache:
  #   image: httpd:latest
  #   container_name: my-apache-app
  #   ports:
  #   - '8080:80'
  #   volumes:
  #   - ../web/helloapp.conf:/usr/local/apache2/sites-enabled/helloapp.conf
  #   networks:
  #     - postgres
  postgres:
    container_name: postgres_container
    image: postgres:14
    command:
      - "postgres"
      - "-c"
      - "max_connections=50"
      - "-c"
      - "shared_buffers=1GB"
      - "-c"
      - "effective_cache_size=4GB"
      - "-c"
      - "work_mem=16MB"
      - "-c"
      - "maintenance_work_mem=512MB"
      - "-c"
      - "random_page_cost=1.1"
      - "-c"
      - "temp_file_limit=10GB"
      - "-c"
      - "log_min_duration_statement=200ms"
      - "-c"
      - "idle_in_transaction_session_timeout=10s"
      - "-c"
      - "lock_timeout=1s"
      - "-c"
      - "statement_timeout=60s"
      - "-c"
      - "shared_preload_libraries=pg_stat_statements"
      - "-c"
      - "pg_stat_statements.max=10000"
      - "-c"
      - "pg_stat_statements.track=all"
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "root"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ../data/:/docker-entrypoint-initdb.d
      - /script.sh:/usr/local/bin/custom-entrypoint.sh
      # - ../datPorphumSales/Migrations/a/init.sh:/docker-entrypoint-initdb.d/initdb.sh
      - habrdb-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    # healthcheck:
    #   test: ["CMD-SHELL", "pg_isready -U user -d habrdb"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5
    #   start_period: 10s
    # restart: unless-stopped
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '1'
    #       memory: 4G
    networks:
      - postgres
  app:
   image: wi1sp/porphum_web:master
   environment:
     - REGISTRY_USERNAME=wi1sp
     - REGISTRY_PASSWORD=dckr_pat_T3-JNWXWL44kl74FN2J--DLWhic
   ports:
     - 5000:80
   depends_on:
     - postgres
   networks:
      - postgres
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:7.2
    environment:
      PGADMIN_DEFAULT_EMAIL: "habrpguser@habr.com"
      PGADMIN_DEFAULT_PASSWORD: "master"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '0.5'
    #       memory: 1G
    networks:
      - postgres

volumes:
  habrdb-data:
  pgadmin-data:

networks:
  postgres:
    driver: bridge